theme: minima

title: Pauls 3D Things
description: >- # this means to ignore newlines until "baseurl:"
  ğŸ‘¨â€ğŸ”¬ I'm a maker: 3D Printing, Electronics, Software
  ğŸ’¡ Follow me on social media to stay up to date
  ğŸ›  Details and How-Tos will be on this website
twitter_username: pauls_3d_things
instagram_username: pauls_3d_things
github_username: pauls-3d-things